### ISSUE TITLE
Editing birthdays from GUI

### ISSUE THREAD

**Issue by Darknetzz** [Miicroo/ha-birthdays#12]
Hi, absolutely love your plugin!

But one thing I'm missing is the ability to edit "unique_id" directly.
I prefer specifying a unique_id so I'm able to change the other attributes without the entity being duplicated.

I am working on a fix for this!

**Comment by Miicroo** [comment]
Sweet! So sorry for the long delay, will pull this into my test container and see that everything works fine!

**Comment by Darknetzz** [comment]
No worries! Thank you! 😄
