### ISSUE TITLE
Version in manifesta

### ISSUE THREAD

**Issue by rikardronnkvist** [Miicroo/ha-birthdays#3]
Have this error in my log...

WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'birthdays'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'birthdays'

Guess it's an easy fix. :)

**Comment by yjajkiew** [comment]
The break is imminent : https://www.home-assistant.io/blog/2021/05/05/release-20215/ 

"Custom integrations that do not have this will be blocked from loading if it’s missing a version in the manifest starting with Home Assistant 2021.6."

**Comment by rikardronnkvist** [comment]
First time trying out the creation of a pull request... so hope that this work:  https://github.com/Miicroo/ha-birthdays/pull/4

**Comment by Miicroo** [comment]
@rirofal Thanks for the PR! I completely missed it but saw that the repo was updated in June with a fix. Seems to be working now so closing this issue :)
