### ISSUE TITLE
Warnings in HA 2021.12.2

### ISSUE THREAD

**Issue by BartEngelen** [Miicroo/ha-birthdays#5]
Hello,

See screenshot.
![image](https://user-images.githubusercontent.com/17978789/146523424-7acc48da-506d-4c79-a9e8-45c827be5f05.png)
Can this be resolved ?
Regards,
Bart Engelen

**Comment by Miicroo** [comment]
@BartEngelen Pushed a fix now, please let me know if it does/doesn't work

**Comment by BartEngelen** [comment]
Thanks!
Problem seems to be solved.
