### ISSUE TITLE
automation suggestion

### ISSUE THREAD

**Issue by pilot1981** [Miicroo/ha-birthdays#6]
How do you suggest to modify automation example to get notification on birthday date, but at time 19.00pm?

regards

**Comment by Miicroo** [comment]
@pilot1981 Hi! Sorry for the very late reply! I recently learned how to build some more complex custom sensors, so I added another automation example where you can use a custom sensor (with days until next birthday, name and age) and a time trigger to send a notification at a specific time. It is not tested on my own setup, so it might need some tweaks! Let me know it works out for you! 😄
