### ISSUE TITLE
using self.async_update_ha_state()

### ISSUE THREAD

**Issue by hvhol** [Miicroo/ha-birthdays#9]
Entity birthdays.lia (<class 'custom_components.birthdays.BirthdayEntity'>) 
is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), 
please report it to the custom integration author.

**Comment by RTS007** [comment]
+1

**Comment by Miicroo** [comment]
Fixed on master branch now, thanks for reporting!
